---
# tasks file for neovim
- name: Install nvim with brew
  community.general.homebrew:
    name: nvim
    state: present
    update_homebrew: true
  become_user: "{{ ansible_user_id }}"
  become: false

- name: Install plugin dependencies
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - fd-find
      - ripgrep
      - luarocks
      - build-essential
      - gcc
      - make
      - cmake
      - unzip
      - curl
      - git
      - nodejs
      - npm
    state: present
    update_cache: true
  become: true

- name: Install pynvim via pip3
  ansible.builtin.pip:
    name: pynvim
    executable: pip3
    state: present
  become: true

- name: Install JetBrains Nerd Fonts and Symbols
  community.general.homebrew_cask:
    name:
      - font-symbols-only-nerd-font
      - font-jetbrains-mono-nerd-font
    state: present
    path: "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:{{ ansible_env.PATH }}"
  become_user: "{{ ansible_user_id }}"
  become: true
  register: brew_fonts

- name: Rebuild font cache {{ brew_fonts }}
  ansible.builtin.command:
    cmd: fc-cache -fv
  changed_when: brew_fonts.changed

- name: Download and add hampuz nvim setup
  ansible.builtin.git:
    repo: https://github.com/Hampuztt/neovim.git
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    version: main
    accept_hostkey: true
